[package]
name = "blind_bid"
version = "0.1.0"
authors = ["CPerezz <carlos@dusk.network>"]
edition = "2018"


[dependencies]
dusk-plonk = {version = "0.1.0"}
dusk-bls12_381 = "0.1.0"
hades252 = {git = "https://github.com/dusk-network/Hades252", tag = "v0.5.0"}
poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", tag = "v0.5.0"}
failure = "0.1.7"
kelvin = "0.13.0"
jubjub = {git = "https://github.com/dusk-network/jubjub", branch = "master"}
num-bigint = "0.2.6"
num-traits = "0.2.11"

[dev-dependencies]
merlin = "2.0.0"
rand = "0.7.3"
rand_core = "0.5.1"