[package]
name = "blind_bid"
version = "0.1.0"
authors = ["CPerezz <carlos@dusk.network>"]
edition = "2018"


[dependencies]
dusk-plonk = "0.2.6"
poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", tag = "v0.6.0-alpha"}
failure = "0.1.7"
kelvin = "0.13.0"
num-bigint = "0.2.6"
num-traits = "0.2.11"

[dev-dependencies]
rand = "0.7.3"
rand_core = "0.5.1"
